### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by ghost** [apacheli/testing#10]
### Description

there is a bug in this program

### Reproduce

run program

### Expected Behavior

it works

### Code/Screenshots/Videos

![h](https://user-images.githubusercontent.com/64013111/134994377-99bb1910-78c3-4e78-a86f-de9e4c9c6eee.png)

### Deno Version

what is deno?

### Build/Platform

TempleOS

### Whirlybird Version

1

### Keywords

broken

**Comment by ghost** [comment]
can you fix pls

**Comment by ghost** [comment]
same

**Comment by apacheli** [comment]
i agree

**Comment by ghost** [comment]
why is this not fixed yet? smh. i'll go use https://github.com/spiralw/playground instead of this broken software
