### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by ghost** [apacheli/testing#7]
### Description

no

### Reproduce

no steps because

### Expected Behavior

it doesn't clean my shoes and doesn't return to moneky

### Code/Screenshots/Videos

no fuck you

### Deno Version

v69.420

### Build/Platform

ur mom

### Whirlybird Version

no i don't

**Comment by apacheli** [comment]
i cant reproduce this bug sorry

**Comment by ghost** [comment]
but i reproduced it!!!!! stop lying!!!!!!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
closed, #13 fixed it!
